name: "Validate OpenAPI specification"
on:
  push:
    branches:
      - main
    tags:
      - v*
    paths-ignore:
      - "**.md"

  pull_request:
    types: [ opened, synchronize ]
    paths-ignore:
      - "**.md"

  workflow_dispatch:

jobs:
  validate-ocpi-v221-specification:
    name: "Validate the OCPI 2.2.1 OpenAPI specification"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Swagger Editor Validator
        uses: swaggerexpert/swagger-editor-validate@v1
        with:
          definition-file: ./2.2.1/api/2.2.1.spec.yml